[package]
name = "nomrs"
version = "0.1.0"
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
rust-crypto = "0.2.36"
hyper = "0.11.6"
lazy_static = "0.2"
futures = "0.1"
tokio-core = "0.1"
